### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by RIPTheBoss** [RIPTheBoss/ETCH-A-SKETCH#1]
- [x] Adjust the colors of the backgrounds
- [x] Add a title to the site
- [x] Reajust the button position 
- [ ] Create a proper UI
- [ ] Add funny color options (random RGB / Fading Black)
- [ ] Add different size of pen
